#!/bin/sh

target=$1

if [ "$target" = "-l" ] 
then
  find $HOME/.ssh -name id_rsa | grep -E "$HOME/.ssh/(.*)/" | cut -d "/" -f 5
  exit 0
fi

if [ -z "$target" ]
then
  echo "Usage:"
  echo " Switch key: $0 <target>"
  echo " List keys:  $0 -l"
  exit 1
fi

src="$HOME/.ssh/$target"
dst="$HOME/.ssh"
echo "Switching to $target ($src)"

if [ -d $HOME/.ssh/$target ]
then
  cp -f $src/id_rsa $dst/id_rsa
  cp -f $src/id_rsa.pub $dst/id_rsa.pub
else
  echo "Key $target does not exist"
fi
